// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630173450_AddEscopoEquipamentoTag")]
    partial class AddEscopoEquipamentoTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AnomaliaDependenciaDetectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnomaliaDetectadaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoRelacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhAnomalia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Impacto")
                        .HasColumnType("TEXT");

                    b.Property<double>("LimiteInferior")
                        .HasColumnType("REAL");

                    b.Property<double>("LimiteSuperior")
                        .HasColumnType("REAL");

                    b.Property<double>("Media")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagDependente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRelacao")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorAtual")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AnomaliaDetectadaId");

                    b.ToTable("AnomaliaDependenciasDetectadas");
                });

            modelBuilder.Entity("AnomaliaDetectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificacaoRisco")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhAnomalia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("ScoreRiscoProcesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TendenciaRisco")
                        .HasColumnType("TEXT");

                    b.Property<string>("TendenciaValor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorRecebido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AnomaliasDetectadas");
                });

            modelBuilder.Entity("EquipamentoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaManutencao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEquipamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Nome")
                        .IsUnique();

                    b.ToTable("EquipamentosIa");
                });

            modelBuilder.Entity("EquipamentoTagIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipamentoIaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Escopo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelDaTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoIaId");

                    b.ToTable("EquipamentoTagsIa");
                });

            modelBuilder.Entity("ProcessoEquipamentoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipamentoIaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelNoProcesso")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessoIaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoIaId");

                    b.HasIndex("ProcessoIaId", "EquipamentoIaId")
                        .IsUnique();

                    b.ToTable("ProcessoEquipamentosIa");
                });

            modelBuilder.Entity("ProcessoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicaoNormal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsequenciasFalha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedimentoRecomendado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Nome")
                        .IsUnique();

                    b.ToTable("ProcessosIa");
                });

            modelBuilder.Entity("ProcessoTagIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelDaTag")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessoIaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoIaId");

                    b.ToTable("ProcessoTagsIa");
                });

            modelBuilder.Entity("TagContextoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcoesRecomendadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausasProvaveis")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContextoCompleto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impactos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModosOperacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoModoOperacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsRelacionadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRepresentacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("TagsContextoIa");
                });

            modelBuilder.Entity("TagDependenciaIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagDependente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName", "TagDependente")
                        .IsUnique();

                    b.ToTable("TagDependenciasIa");
                });

            modelBuilder.Entity("TagIaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConfiguracao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IaAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("TagsIaConfig");
                });

            modelBuilder.Entity("TagPerfilIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amplitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTreinamento")
                        .HasColumnType("TEXT");

                    b.Property<double>("DesvioPadrao")
                        .HasColumnType("REAL");

                    b.Property<double>("Maximo")
                        .HasColumnType("REAL");

                    b.Property<double>("Media")
                        .HasColumnType("REAL");

                    b.Property<double>("Minimo")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentualZeros")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantidadePicos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOutliersRemovidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosHistorico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosUsados")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VariacaoMedia")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("PerfisIa");
                });

            modelBuilder.Entity("AnomaliaDependenciaDetectada", b =>
                {
                    b.HasOne("AnomaliaDetectada", "AnomaliaDetectada")
                        .WithMany("Dependencias")
                        .HasForeignKey("AnomaliaDetectadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnomaliaDetectada");
                });

            modelBuilder.Entity("EquipamentoTagIa", b =>
                {
                    b.HasOne("EquipamentoIa", "EquipamentoIa")
                        .WithMany("Tags")
                        .HasForeignKey("EquipamentoIaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipamentoIa");
                });

            modelBuilder.Entity("ProcessoEquipamentoIa", b =>
                {
                    b.HasOne("EquipamentoIa", "Equipamento")
                        .WithMany("Processos")
                        .HasForeignKey("EquipamentoIaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessoIa", "Processo")
                        .WithMany("Equipamentos")
                        .HasForeignKey("ProcessoIaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ProcessoTagIa", b =>
                {
                    b.HasOne("ProcessoIa", "ProcessoIa")
                        .WithMany("Tags")
                        .HasForeignKey("ProcessoIaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessoIa");
                });

            modelBuilder.Entity("AnomaliaDetectada", b =>
                {
                    b.Navigation("Dependencias");
                });

            modelBuilder.Entity("EquipamentoIa", b =>
                {
                    b.Navigation("Processos");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ProcessoIa", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
