// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624193859_AddRiscoProcessoNaAnomaliaV2")]
    partial class AddRiscoProcessoNaAnomaliaV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AnomaliaDependenciaDetectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnomaliaDetectadaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoRelacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhAnomalia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Impacto")
                        .HasColumnType("TEXT");

                    b.Property<double>("LimiteInferior")
                        .HasColumnType("REAL");

                    b.Property<double>("LimiteSuperior")
                        .HasColumnType("REAL");

                    b.Property<double>("Media")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagDependente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRelacao")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorAtual")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AnomaliaDetectadaId");

                    b.ToTable("AnomaliaDependenciasDetectadas");
                });

            modelBuilder.Entity("AnomaliaDetectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificacaoRisco")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhAnomalia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("ScoreRiscoProcesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorRecebido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AnomaliasDetectadas");
                });

            modelBuilder.Entity("TagContextoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcoesRecomendadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausasProvaveis")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContextoCompleto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Criticidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impactos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModosOperacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoModoOperacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsRelacionadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRepresentacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("TagsContextoIa");
                });

            modelBuilder.Entity("TagDependenciaIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagDependente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName", "TagDependente")
                        .IsUnique();

                    b.ToTable("TagDependenciasIa");
                });

            modelBuilder.Entity("TagIaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConfiguracao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IaAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("TagsIaConfig");
                });

            modelBuilder.Entity("TagPerfilIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amplitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTreinamento")
                        .HasColumnType("TEXT");

                    b.Property<double>("DesvioPadrao")
                        .HasColumnType("REAL");

                    b.Property<double>("Maximo")
                        .HasColumnType("REAL");

                    b.Property<double>("Media")
                        .HasColumnType("REAL");

                    b.Property<double>("Minimo")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentualZeros")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantidadePicos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOutliersRemovidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosHistorico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosUsados")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VariacaoMedia")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("PerfisIa");
                });

            modelBuilder.Entity("AnomaliaDependenciaDetectada", b =>
                {
                    b.HasOne("AnomaliaDetectada", "AnomaliaDetectada")
                        .WithMany("Dependencias")
                        .HasForeignKey("AnomaliaDetectadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnomaliaDetectada");
                });

            modelBuilder.Entity("AnomaliaDetectada", b =>
                {
                    b.Navigation("Dependencias");
                });
#pragma warning restore 612, 618
        }
    }
}
