// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618191201_AddControleOutliersPerfil")]
    partial class AddControleOutliersPerfil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TagIaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConfiguracao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IaAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("TagsIaConfig");
                });

            modelBuilder.Entity("TagPerfilIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amplitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTreinamento")
                        .HasColumnType("TEXT");

                    b.Property<double>("DesvioPadrao")
                        .HasColumnType("REAL");

                    b.Property<double>("Maximo")
                        .HasColumnType("REAL");

                    b.Property<double>("Media")
                        .HasColumnType("REAL");

                    b.Property<double>("Minimo")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentualZeros")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantidadePicos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOutliersRemovidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosHistorico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistrosUsados")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VariacaoMedia")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TagName")
                        .IsUnique();

                    b.ToTable("PerfisIa");
                });
#pragma warning restore 612, 618
        }
    }
}
